
import { ClerkProvider } from '@clerk/nextjs'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ToastProvider } from '@/components/providers/ToasterProvider'
import { Toaster } from 'sonner';
import ConfettiProvider from '@/components/providers/ConfettiProvider'

const inter = Inter({ subsets: ['latin'] })


export const metadata: Metadata = {
  title: 'Sell Courses',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <ToastProvider />
          <ConfettiProvider />
          <Toaster richColors position="top-center"/>
          {/* <Toaster richColors position="top-right" /> */}
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}
